s1=float(input("enter the marks of studens 1:"))
s2=float(input("enter marks of student 2:"))
s3=float(input("enter marks of subject3:"))
s4=float(input("enter marks of subject4:"))
s5=float(input("enter marks of subject5:"))
total=s1+s2+s3+s4+s5
percentage=(total/500)*100
print("total marks=",total)
print("percentage=",percentage,"%")